language: cpp
compiler: clang
script:
  - git remote add reviewer https://github.com/ssaavedra/pfc-vacmatch.git
  - git fetch reviewer latest-review
  - git branch -f latest-review reviewer/latest-review
  - make all
  - pdf2djvu --no-page-titles -j2 -o root.djvu root.pdf
  - make root-diff.pdf || true
  - pdf2djvu --no-page-titles -j2 -o root-diff.djvu root-diff.pdf
  
addons:
  apt:
    packages:
    - autoconf
    - automake
    - djvulibre-bin
    - fonts-linuxlibertine
    - gettext
    - libdjvulibre-dev
    - libexiv2-dev
    - libfontconfig1-dev
    - libgraphicsmagick++1-dev
    - libpoppler-cpp-dev
    - libpoppler-dev
    - libpoppler-glib-dev
    - libxml2-utils
    - pkg-config
    - python-docutils
    - python-imaging
    - python-nose
    - uuid-dev

cache:
  ccache
  directories:
    - $HOME/texlive
    - $HOME/latexdiff
    - $HOME/pdf2djvu
    - $HOME/.ccache

before_install:
  - [[ -d ~/texlive ]] || curl -L https://github.com/yihui/ubuntu-bin/releases/download/latest/texlive.tar.gz | tar zxC ~
  - [[ -d ~/pdf2djvu ]] || curl -L https://bitbucket.org/jwilk/pdf2djvu/downloads/pdf2djvu-0.9.4.tar.xz | tar xJC ~
  - [[ -d ~/latexdiff ]] || git clone --depth=1 https://github.com/ssaavedra/latexdiff.git ~/latexdiff
install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - PATH=$HOME/latexdiff:$PATH
  - tlmgr install collection-langspanish
  - tlmgr install minitoc lettrine times rsfs cm-super
  - tlmgr install avantgar tex4ht
  - export PATH="/usr/lib/ccache:$PATH"
  - [[ -d ~/pdf2djvu ]] || mkdir -p ~/pdf2djvu && (cd ~/pdf2djvu-0.9.4 && ./configure --prefix=$HOME/pdf2djvu && make && make install)
  - export PATH=$HOME/pdf2djvu/bin:$PATH
deploy:
  provider: releases
  api_key:
    secure: jBdUmKPvTnGVHhQ4TK6btEyyI1ozeSOceAQ4fuCRm267WuMd7VXlJ60/nV+ntDNUwyOt03kV+O3ZN8+XmdtWU/SOKa+Jm1Icj3hS7oxItENRrnld8oS4YVLYMyhXJxVccYCtvL/A57R23qro/t6xuJVdv5bna7JihOQPLFt8Q98wOVEwrHcbzzD4jHIH27OBfZp/i0iO6PjQywOalq1P5Vf8GXI9AtGW9i8n1jKOCf0bJSnwSAR+O4KjGll0GFf/1bbJ8ZaOpPpKVolHf3s6MsnlB0YELEjgeANkaovTT0N+ecKnzEgEs9AWKAL27oC7pREi7oiMfGNdiL7dJDKGT5EI+aLzqunXWBg1zpYKjMBg8I2FYI1Gjy+GZD3OxjC9d27OtE0B4vtaqbiEdJyoRGhespMrRuHUIBIWSEcX3OnMtQ+8/RiDQcFDPleFI9EwWAQJEsUI5Jse21z5uK93J5pnjO597Jvi+OkvdlnYQMteSSuQAnqhaSnwNuU6/31v1lfCT4Je7nk4Vq4dy11qhRAYO/HjiuP2ysHDxE9eKPiStL9dgOqVtYGMQEo4WYr8uLcbfWbvPVKPg0l5OdxIib5NhNI1E8QAhwL4kYj1xgh7VIWofEGeuB0KpagjLCc5J6uw36Z4duyrC9yHmLoW93Vu7DLG7oO/Xp08Ez/c1us=
  file:
    - root.pdf
    - root.djvu
    - root-diff.pdf
    - root-diff.djvu
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
